version: "3.9"
services:
  product: 
   image: app/account
   build: account



account:  
    image: app/account
    build: account
    volumes: 
    - ./account:/app
    

    account-database:
      image: mongo
      container_name: account-database
      ports:
       - 27017:27017
    env_file: account/.env
